Create IBAN validator in message/transaction detail for increased speed
genkgo/camt pull request #110
Opened 2021-11-23 12:31 UTC by stephanvdhorn

We encountered a speed issue where if you have a lot of entries it creates an IBAN object for each IBAN found. The IBAN class creates a validator (external package) which reads a YAML file containing rules that is about 1200 lines. So if you, for example, have 700 IBANs that need to be validated, it needs to parse that file 700 times. Which causes slowdown.

This PR changes it so the validator is created once on the Message and once on the TransactionDetail and it will keep re-using that instead of creating a new Validator each time.

2021-11-23 13:52 UTC, PowerKiKi requested changes
That sounds like a good thing to improve, however I think it should be done in https://github.com/jschaedl/iban-validation directly so all upstream users can benefit from that too.

Could you please open an issue over there, explaining your findings, and linking it here ?

If that improvement is rejected over there, we can re-consider this PR.

2021-11-24 12:53 UTC, stephanvdhorn commented
New issue: https://github.com/jschaedl/iban-validation/issues/61

It seems unlikely the developer will respond considering there's been no replies/merges this year as far as I can see. But I added a suggestion in the issue how it may be improved. It still makes sense to me if the validator is created once (or twice) and re-used however.

2021-11-29 11:25 UTC, stephanvdhorn commented
My apologies, I actually got a reply pretty quickly.

I temporarily changed the branch of the IBAN package in my local dev environment to `issue-61` to see how much faster it was. And it went from 32-37 seconds to about 1.4 seconds so that's a huge speed increase! Hope it can get merged quickly as we need it ASAP.

2021-11-29 11:27 UTC, stephanvdhorn commented
My changes here in the CAMT package can be ignored once the IBAN package is updated.

2021-12-06 13:34 UTC, PowerKiKi commented
The new release https://github.com/jschaedl/iban-validation/releases/tag/v1.8.0 includes the performance improvement. And it can be leveraged by a simple `composer update`, without any modification to this package.

Thanks for your contribution !

2021-12-06 13:34 UTC, closed without merging