Add organisation id for related parties and add proprietary amount
genkgo/camt pull request #141
Opened 2023-03-07 13:30 UTC by marac990

2023-03-10 04:16 UTC, PowerKiKi requested changes
OrgId seems fine, as long as the `null` thing is fixed.

I am less sure about the proprietary amount though. You are reading `Tp`, and according to spec this is:

> 6.1.3.1.5.1 Type <Tp>
> Presence: [1..1]
> Definition: Specifies the type of amount.
> Datatype: "Max35Text" on page 372

It does not sound like an amount of money at all. It could be pretty much any free text. What data to you see in this field ? Instead should you not read `6.1.3.1.5.2 Amount <Amt>` ?

Also the proprietary amount is not covered by any tests, and this is a no-go. You should at the very least add a realistic example of data in regression tests.

2023-03-10 04:16 UTC, PowerKiKi commented on src/Decoder/EntryTransactionDetail.php
> +        $relatedPartyType->setOrgId((string)$orgId);
Model accept `null`, but here you cast `null` into `""`. So the model will never be `null`. IMHO this is wrong and the you should never set an orgId if it is non-existent.

2023-03-14 18:14 UTC, marac990 commented
> 

Hi, regarding this I've added a real TxDtls from the statement that we receive from the bank (of course real data is changed for some dummy data). And in our case we need that parsed.

2023-05-01 10:42 UTC, PowerKiKi requested changes
Checks on this PR are still failing. Everything need to be green, and the PR should be rebased on top of master, before I can properly review the whole thing.

2023-05-01 10:42 UTC, PowerKiKi commented on src/DTO/Creditor.php
> +    public function setOrgId(string $orgId): void
`orgId` must be renamed into `organisationId`, in the private member, setter and getter.

2023-08-02 11:38 UTC, orukaz commented
Yes, Related Parties and ID-s are very neede, maybe I can help with that:

<RltdPties>
                            <Dbtr>
                                <Nm>Some person</Nm>
                                <Id>
                                    <PrvtId>
                                        <Othr>
                                            <Id>12345678</Id>
                                            <SchmeNm>
                                                <Cd>NIDN</Cd>
                                            </SchmeNm>
                                        </Othr>
                                    </PrvtId>
                                </Id>
                            </Dbtr>
                            
                            
                            
<RltdPties>
                            <Dbtr>
                                <Nm>Business Ltd</Nm>
                                <Id>
                                    <OrgId>
                                        <Othr>
                                            <Id>675675676</Id>
                                            <SchmeNm>
                                                <Cd>COID</Cd>
                                            </SchmeNm>
                                        </Othr>
                                    </OrgId>
                                </Id>
                            </Dbtr>

2025-05-14 05:12 UTC, PowerKiKi commented
I'm closing this, because there is no activity and it's been partially implemented in #168. Any further work should be taking into consideration those new improvements.

2025-05-14 05:12 UTC, closed without merging