Read account names
genkgo/camt pull request #161
Opened 2024-11-13 18:39 UTC by juliangums

2024-11-14 02:49 UTC, PowerKiKi requested changes
Also this will require adding tests before being merged. An easy to do that is to add the appropriate file in `test/data`.

2024-11-14 02:49 UTC, PowerKiKi commented on src/DTO/NamedAccount.php
> +class NamedAccount extends Account
We should not introduce a new class here. The spec defines `Acc` as type `CashAccount25`. And `CashAccount25` defines an object that has must have an ID (IBAN or Othr), and may have a name. Thus the name property must be added on the existing `IbanAccount`

2025-02-06 12:55 UTC, juliangums commented
@PowerKiKi I've done those things

2025-03-05 06:53 UTC, closed without merging

2025-03-05 06:57 UTC, PowerKiKi commented
Sorry for the late review. I re-worked your work into #166 and released as 2.9.0. This excludes the recent commit that modify the specification, as it should probably not live in this project.